#include <bits/stdc++.h>
using namespace std;

#include "Lexer.h"
#include "Parser.h"
#include "Semantic.h"
#include "CodeGen.h"

bool hasError = false;


int main()
{
#ifdef _WIN32
    system("chcp 65001 > nul");
#endif


    cout
        << "===== CODE GENERATION TEST =====\n\n";


    string code = R"(
পূর্ণসংখ্যা গণনা = ০;
পূর্ণসংখ্যা দ্বিগুণ = ১;

যতক্ষণ(গণনা < ৫)
{
    দ্বিগুণ = দ্বিগুণ * ২;

    যদি(গণনা == ৩)
    {
        দ্বিগুণ = দ্বিগুণ + ১০;
    }

    গণনা = গণনা + ১;
}
)";


    cout
        << "Source Code:\n"
        << code
        << "\n";


    // ========================================================
    // Lexer
    // ========================================================

    Lexer lexer(code);

    vector<Token> tokens =
        lexer.tokenize();


    // ========================================================
    // Parser
    // ========================================================

    Parser parser(tokens);

    ProgramPtr ast =
        parser.parse();


    if (hasError)
    {
        cout
            << "Codegen Test Failed: "
            << "Parsing error detected.\n";

        return 1;
    }


    // ========================================================
    // Semantic
    // ========================================================

    SemanticAnalyzer semantic;

    semantic.analyze(ast);


    if (hasError)
    {
        cout
            << "Codegen Test Failed: "
            << "Semantic error detected.\n";

        return 1;
    }


    // ========================================================
    // Code Generation
    // ========================================================

    CodeGenerator generator;

    string generatedCode =
        generator.generate(ast);


    cout
        << "-----------------------------\n";

    cout
        << "Generated Python:\n";

    cout
        << "-----------------------------\n";

    cout
        << generatedCode;

    cout
        << "-----------------------------\n";


    ofstream outFile(
        "codegen_test_output.py"
    );


    if (!outFile.is_open())
    {
        cout
            << "Could not create "
            << "codegen_test_output.py\n";

        return 1;
    }


    outFile
        << "# Generated by codegen_test.cpp\n\n"
        << generatedCode
        << "\n"
        << "print('গণনা =', গণনা)\n"
        << "print('দ্বিগুণ =', দ্বিগুণ)\n";


    outFile.close();


    cout
        << "\nCodegen Test Passed.\n";

    cout
        << "Generated file: "
        << "codegen_test_output.py\n";


    return 0;
}